import type {PublicTopicId} from '../intelligence/publicFindings';

export type FocusTarget=
  |{kind:'story';topicId:PublicTopicId;periodId:string;metricIds:string[]}
  |{kind:'value-leakage';metricId:'launch-tax-gap'|'launch-benefit-error'|'launch-productivity'|'interest';periodId:string}
  |{kind:'national';periodId:string;flowId?:string};
export type Claim={id:string;claim:string;botwReading:string;doesNotProve:string;evidenceIds:string[];focusTarget:FocusTarget};
export type JourneyStep={eyebrow:string;title:string;value:string;explanation:string;limit:string;evidenceIds:string[];focusTarget:FocusTarget};
export type Journey={id:'immigration'|'health';title:string;question:string;steps:JourneyStep[]};

export const claims:Claim[]=[
  {id:'tax-gap',claim:'The estimated UK tax gap was £59.2bn in 2024–25.',botwReading:'HMRC estimates this as 6.4% of theoretical tax liabilities.',doesNotProve:'It is not an estimate of tax evasion alone or an amount that can all be collected.',evidenceIds:['launch-tax-gap'],focusTarget:{kind:'value-leakage',metricId:'launch-tax-gap',periodId:'2024-25'}},
  {id:'benefit-error',claim:'Benefits were overpaid by an estimated £9.9bn in FYE 2026.',botwReading:'The total includes fraud, claimant error and official error.',doesNotProve:'It does not show that every overpayment was claimant fraud, deliberate or recoverable.',evidenceIds:['launch-benefit-error'],focusTarget:{kind:'value-leakage',metricId:'launch-benefit-error',periodId:'2025-26'}},
  {id:'productivity',claim:'Public-service productivity rose an estimated 0.9% in 2025.',botwReading:'ONS classifies this aggregate as statistics in development; it remained 2.5% below 2019.',doesNotProve:'It does not establish cash savings, the cause of change or that every service improved.',evidenceIds:['launch-productivity'],focusTarget:{kind:'value-leakage',metricId:'launch-productivity',periodId:'2025-26'}},
  {id:'migration',claim:'Net migration peaked around 944,000, then fell to 204,000.',botwReading:'The rolling annual series was already falling before the July 2024 handover and fell further afterwards.',doesNotProve:'Chronology cannot apportion the fall between policies, governments or other contributors.',evidenceIds:['story-ons-net-migration'],focusTarget:{kind:'story',topicId:'immigration',periodId:'2025-26',metricIds:['net-migration']}},
  {id:'housing',claim:'Temporary accommodation reached 135,580 households at 31 March 2026.',botwReading:'The England point-in-time count continued to rise across the accepted five-year series.',doesNotProve:'It is not the number of people or the total households experiencing homelessness over a year.',evidenceIds:['story-housing-temporary-accommodation'],focusTarget:{kind:'story',topicId:'housing',periodId:'2025-26',metricIds:['housing-temporary-accommodation']}},
];

const f=(topicId:PublicTopicId,periodId:string,metricIds:string[]):FocusTarget=>({kind:'story',topicId,periodId,metricIds});
export const journeys:Record<'immigration'|'health',Journey>={
  immigration:{id:'immigration',title:'Did Labour inherit falling immigration?',question:'What was inherited, and what happened next?',steps:[
    {eyebrow:'01 · THE RISE',title:'Net migration rose sharply after 2021',value:'466,000',explanation:'The comparable year-ending series was about 466,000 at June 2021 and continued upwards.',limit:'A rolling annual estimate is not a point-in-time government score.',evidenceIds:['story-ons-net-migration'],focusTarget:f('immigration','2021-22',['net-migration'])},
    {eyebrow:'02 · POLICY CONTEXT',title:'Work and graduate routes expanded',value:'2021–22',explanation:'The Graduate route opened and care workers became eligible for the Health and Care visa.',limit:'Sequence alone does not quantify either policy’s contribution.',evidenceIds:['story-graduate-route','story-care-route'],focusTarget:f('immigration','2021-22',['net-migration'])},
    {eyebrow:'03 · PEAK',title:'The revised series reached its high point',value:'944,000',explanation:'Net migration peaked in the year ending March 2023.',limit:'The estimate has been revised and the year spans more than one administration.',evidenceIds:['story-ons-net-migration'],focusTarget:f('immigration','2022-23',['net-migration'])},
    {eyebrow:'04 · RESTRICTIONS',title:'Several restrictions took effect in early 2024',value:'JAN–APR 2024',explanation:'Student and care-worker dependant rules tightened and the general Skilled Worker salary threshold rose.',limit:'A policy date is not evidence of its measured effect.',evidenceIds:['story-student-dependants','story-care-dependants','story-skilled-threshold'],focusTarget:f('immigration','2023-24',['net-migration'])},
    {eyebrow:'05 · BEFORE HANDOVER',title:'The measure was already falling',value:'649,000',explanation:'The latest pre-handover annual estimate, for the year ending June 2024, was below the peak.',limit:'The annual window overlaps earlier policy and behaviour.',evidenceIds:['story-ons-net-migration'],focusTarget:f('immigration','2024-25',['net-migration'])},
    {eyebrow:'06 · HANDOVER',title:'Government changed on 5 July 2024',value:'5 JUL 2024',explanation:'The handover sits inside overlapping measurement periods rather than between clean annual blocks.',limit:'BOTW does not assign the inherited level to one party.',evidenceIds:['story-government-history'],focusTarget:f('immigration','2024-25',['net-migration'])},
    {eyebrow:'07 · WHAT FOLLOWED',title:'The fall continued after the handover',value:'204,000',explanation:'Provisional net migration fell to 204,000 in the year ending June 2025; 64,426 people awaited an initial asylum decision at December 2025.',limit:'The timeline cannot apportion the fall between governments or individual measures.',evidenceIds:['story-ons-net-migration','story-asylum-awaiting'],focusTarget:f('immigration','2025-26',['net-migration','asylum-awaiting-initial'])},
  ]},
  health:{id:'health',title:'Britain spent more on Health. Did the NHS get better?',question:'Follow money, capacity, activity and waiting together.',steps:[
    {eyebrow:'01 · MONEY',title:'Health and social-care spending increased',value:'£313.7bn',explanation:'UK public spending provides the fiscal context for the 2025–26 complete outturn.',limit:'The operational measures that follow cover NHS England, not the whole UK.',evidenceIds:['e-health'],focusTarget:f('health','2025-26',['health-spend'])},
    {eyebrow:'02 · CAPACITY',title:'The NHS workforce was larger',value:'1.38m FTE',explanation:'Hospital and Community Health Service full-time-equivalent staff in England increased across the comparable period.',limit:'This excludes primary care and does not itself measure productivity.',evidenceIds:['story-health-workforce'],focusTarget:f('health','2025-26',['health-workforce'])},
    {eyebrow:'03 · ACTIVITY',title:'More pathways were completed in March',value:'1.71m',explanation:'Admitted plus non-admitted referral-to-treatment pathways completed in March 2026 rose.',limit:'This is a monthly count, not annual output, and does not describe case complexity or quality.',evidenceIds:['story-health-activity'],focusTarget:f('health','2025-26',['health-rtt-activity'])},
    {eyebrow:'04 · OUTCOME',title:'The waiting list remained very large',value:'7.11m',explanation:'Incomplete referral-to-treatment pathways at 31 March 2026 remained above March 2022.',limit:'Pathways are not unique patients.',evidenceIds:['story-health-rtt'],focusTarget:f('health','2025-26',['health-rtt-waiting'])},
    {eyebrow:'05 · STANDARD',title:'The 18-week standard remained unmet',value:'65.3%',explanation:'The share of incomplete pathways waiting no more than 18 weeks was below the 92% constitutional standard.',limit:'This is one operational performance measure, not a complete account of care.',evidenceIds:['story-health-rtt'],focusTarget:f('health','2025-26',['health-rtt-18-week'])},
    {eyebrow:'06 · PRODUCTIVITY CONTEXT',title:'Aggregate public-service productivity rose',value:'+0.9%',explanation:'ONS estimates output grew faster than inputs in calendar 2025 across public services.',limit:'This aggregate cannot explain NHS waiting-list changes or cash savings.',evidenceIds:['launch-productivity'],focusTarget:f('health','2025-26',['health-rtt-activity'])},
    {eyebrow:'07 · CONCLUSION',title:'More resource and activity did not clear the backlog',value:'MIXED',explanation:'Spending and workforce rose; March activity increased and waiting fell recently, but remained above March 2022.',limit:'Observed co-movement is not proof that spending caused, or failed to prevent, any outcome.',evidenceIds:['e-health','story-health-workforce','story-health-activity','story-health-rtt'],focusTarget:f('health','2025-26',['health-spend','health-workforce','health-rtt-activity','health-rtt-waiting'])},
  ]},
};

export type KeyEvidence={display:string;label:string;period:string};
export type SupportedQuestion={id:string;canonical:string;aliases:string[];answer:string;reading:string;limit:string;evidenceIds:string[];keyEvidence:KeyEvidence;focusTarget:FocusTarget;keywords:string[]};
export type AskAnswer={title:string;answer:string;claim:Claim;keyEvidence:KeyEvidence;suggestions:string[];score:number};
const story=(topicId:PublicTopicId,periodId:string,...metricIds:string[]):FocusTarget=>({kind:'story',topicId,periodId,metricIds});
const national=(periodId:string,flowId?:string):FocusTarget=>({kind:'national',periodId,flowId});
const value=(metricId:'launch-tax-gap'|'launch-benefit-error'|'launch-productivity'|'interest',periodId:string):FocusTarget=>({kind:'value-leakage',metricId,periodId});
const q=(id:string,canonical:string,aliases:string[],answer:string,reading:string,limit:string,evidenceIds:string[],keyEvidence:KeyEvidence,focusTarget:FocusTarget,keywords:string[]):SupportedQuestion=>({id,canonical,aliases,answer,reading,limit,evidenceIds,keyEvidence,focusTarget,keywords});
export const supportedQuestions:SupportedQuestion[]=[
  q('money-source','Where does Britain’s public money come from?',['where does the money come from','where is public money from'],'Taxes and other receipts provide most public money; borrowing closes the gap between income and spending.','The Wall balances recorded public income and borrowing against spending.','This accounting view does not judge whether any tax or borrowing choice is desirable.',['e-income'],{display:'£1.360tn',label:'total public money',period:'2025–26'},national('2025-26'),['money','come','from','income','borrow']),
  q('largest-spend','What does Britain spend most on?',['where does britain spend most','biggest area of spending','where does all our tax money go','whats the biggest thing britain spends money on'],'Health and social care is the largest spending destination on the current Wall.','The comparison uses the same UK public-spending framework across destinations.','A large total does not show service quality or value for money.',['e-health'],{display:'£313.7bn',label:'health and social care spending',period:'2025–26'},national('2025-26','health'),['spend','most','largest','biggest']),
  q('total-spend','How much does Britain spend in total?',['total public spending','what is total spending','how much does britain spend altogether'],'The latest complete Wall balances £1.360tn of total public money.','This is the selected UK fiscal-period total used by the Wall.','It is not household income, GDP or a forecast.',['e-income'],{display:'£1.360tn',label:'total public money',period:'2025–26'},national('2025-26'),['total','spend','public','money']),
  q('health-100','How much of every £100 goes to health?',['every £100 health','how much goes on health'],'Health and social care accounts for about £23.1 of every £100 on the current Wall.','The numerator and total are UK public spending for the same fiscal period.','It does not measure NHS England performance.',['e-health'],{display:'£23.1',label:'of every £100',period:'2025–26'},national('2025-26','health'),['health','100','every','goes']),
  q('health-spend','How much does Britain spend on health?',['how much do we spend on the nhs','how much is nhs spending'],'UK health and social-care spending was £313.7bn in 2025–26.','This is the UK public-spending total used by the current Wall.','It is fiscal context, not a measure of NHS England performance or health outcomes.',['e-health'],{display:'£313.7bn',label:'health and social care spending',period:'2025–26'},national('2025-26','health'),['health','nhs','spend','spending']),
  q('debt-interest','How much goes on debt interest?',['how much is debt interest','cost of debt interest'],'Debt interest and related transactions were £130.3bn in 2025–26, about £9.6 of every £100.','The Wall presents the official outturn in the selected fiscal frame.','It is not all avoidable waste or a frontline-service measure.',['e-interest'],{display:'£130.3bn',label:'debt interest and related transactions',period:'2025–26'},value('interest','2025-26'),['debt','interest','cost']),
  q('health-rise','Has health spending increased?',['did health spending rise','health spend increased','has nhs spending gone up'],'Health and social-care spending increased across the displayed five-year comparison.','This is UK fiscal spending context alongside England operational measures.','The increase alone cannot prove improved outcomes.',['e-health'],{display:'£313.7bn',label:'health and social care spending',period:'2025–26'},story('health','2025-26','health-spend'),['health','spend','increase','rise']),
  q('health-since-2021','How has health changed since 2021?',['nhs change since 2021','health since 2021'],'Spending, workforce and March activity rose; the waiting list remained above March 2022 despite a recent fall.','BOTW reads money, capacity, activity and waiting together.','Observed co-movement is not proof that spending caused the operational changes.',['e-health','story-health-workforce','story-health-activity','story-health-rtt'],{display:'7.11m',label:'incomplete RTT pathways',period:'March 2026'},story('health','2025-26','health-spend','health-workforce','health-rtt-activity','health-rtt-waiting'),['health','change','since','2021']),
  q('waiting-falling','Is the NHS waiting list falling?',['are nhs waiting lists coming down','is waiting list falling'],'Yes, the England RTT waiting list fell from its March 2024 peak, but remained above March 2022.','Incomplete pathways declined to 7.11m at March 2026.','Pathways are not unique patients, and the fall does not establish its cause.',['story-health-rtt'],{display:'7.11m',label:'incomplete RTT pathways',period:'March 2026'},story('health','2025-26','health-rtt-waiting'),['nhs','waiting','list','fall','coming','down']),
  q('waiting-peak','When did the NHS waiting list peak?',['when was waiting list highest','nhs backlog peak','when was the nhs waiting list highest'],'In this five-year comparison, the England RTT waiting list peaked at 7.54m in March 2024.','The series then fell in March 2025 and March 2026.','This is a snapshot of incomplete pathways, not unique patients.',['story-health-rtt'],{display:'7.54m',label:'incomplete RTT pathways',period:'March 2024'},story('health','2023-24','health-rtt-waiting'),['nhs','waiting','peak','highest']),
  q('eighteen-week','Is 18-week NHS performance improving?',['is the 18 week standard improving','are more patients within 18 weeks'],'The share within 18 weeks improved to 65.3%, but remained below the 92% constitutional standard.','The accepted series shows recent improvement after an earlier fall.','This single measure is not a complete account of care quality.',['story-health-rtt'],{display:'65.3%',label:'of RTT pathways within 18 weeks',period:'March 2026'},story('health','2025-26','health-rtt-18-week'),['18','week','improve','standard','within']),
  q('nhs-better','Did the NHS get better as spending rose?',['is nhs better as spending increased','did more spending improve nhs','did more nhs money improve things'],'The picture is mixed: spending, workforce and March activity rose, while waiting improved recently but remained above March 2022.','BOTW shows these measures together without assigning causation.','The comparison cannot prove that spending caused, or failed to prevent, any outcome.',['e-health','story-health-workforce','story-health-activity','story-health-rtt'],{display:'MIXED',label:'money, capacity, activity and waiting',period:'2021–22 to 2025–26'},story('health','2025-26','health-spend','health-workforce','health-rtt-activity','health-rtt-waiting'),['nhs','better','spend','rise']),
  q('workforce-waiting','Did a larger NHS workforce reduce waiting?',['workforce and waiting list','more nhs staff reduce waits'],'The workforce grew and the waiting list fell recently, but remained above March 2022.','The two accepted series move together only at a broad annual comparison level.','This does not prove the workforce change caused the waiting-list change.',['story-health-workforce','story-health-rtt'],{display:'1.38m',label:'FTE staff',period:'March 2026'},story('health','2025-26','health-workforce','health-rtt-waiting'),['workforce','staff','waiting','reduce']),
  q('inherit-migration','Did Labour inherit falling immigration?',['was migration already falling before labour','did labour inherit falling migration'],'Yes. The rolling net-migration estimate had fallen from its peak before the July 2024 handover, then fell further.','The latest pre-handover annual estimate was 649,000; the latest displayed estimate is 204,000.','Overlapping annual periods cannot apportion the fall between governments.',['story-ons-net-migration','story-government-history'],{display:'204k',label:'net migration',period:'year ending June 2025'},story('immigration','2025-26','net-migration'),['labour','inherit','migration','fall','before']),
  q('migration-cause','Did Labour cause immigration to fall?',['did labour make immigration fall'],'BOTW cannot establish that Labour caused the fall in net migration.','The rolling estimate was already below its peak before the July 2024 handover and fell further afterwards.','Overlapping annual periods and multiple contributors prevent this timeline from apportioning causation between governments or policies.',['story-ons-net-migration','story-government-history'],{display:'204k',label:'net migration',period:'year ending June 2025'},story('immigration','2025-26','net-migration'),['labour','cause','migration','fall']),
  q('migration','What is net migration?',['what happened to net migration','what happened to immigration','latest net migration'],'The latest displayed provisional estimate is 204,000 for the year ending June 2025.','Net migration is immigration minus emigration over a rolling annual period.','The estimate may be revised and does not explain why people moved.',['story-ons-net-migration'],{display:'204k',label:'net migration',period:'year ending June 2025'},story('immigration','2025-26','net-migration'),['net','migration','latest','happened']),
  q('migration-peak','When did net migration peak?',['when was migration highest','when was immigration highest','migration peak'],'The revised series peaked at about 944,000 in the year ending March 2023.','The rolling annual estimate fell after that high point.','A peak date cannot by itself identify policy causes.',['story-ons-net-migration'],{display:'944k',label:'net migration',period:'year ending March 2023'},story('immigration','2022-23','net-migration'),['migration','peak','highest']),
  q('backlog-falling','Is the asylum backlog falling?',['is asylum waiting falling','are fewer people awaiting asylum decisions'],'Yes. People awaiting an initial decision fell from the displayed peak to 64,426 at December 2025.','The measure is a point-in-time Home Office count.','It does not show decision quality or later appeals.',['story-asylum-awaiting'],{display:'64,426',label:'people awaiting an initial asylum decision',period:'December 2025'},story('immigration','2025-26','asylum-awaiting-initial'),['asylum','backlog','waiting','fall']),
  q('backlog-peak','When did the asylum backlog peak?',['when was asylum backlog highest','asylum waiting peak'],'In the displayed series, the initial-decision backlog peaked at 160,919 people in December 2022.','The count subsequently declined.','The series does not cover every stage of the asylum system.',['story-asylum-awaiting'],{display:'160,919',label:'people awaiting an initial asylum decision',period:'December 2022'},story('immigration','2022-23','asylum-awaiting-initial'),['asylum','backlog','peak','highest']),
  q('decisions','Are asylum decisions increasing?',['are more asylum decisions being made','asylum decisions increasing'],'The displayed substantive-decision count reached 135,740 in calendar 2025, above earlier comparison years.','This is system output, shown separately from the people awaiting an initial decision.','More decisions do not by themselves prove faster, fairer or final resolution.',['story-asylum-decisions'],{display:'135,740',label:'people receiving substantive asylum decisions',period:'calendar 2025'},story('immigration','2025-26','asylum-substantive-decisions'),['asylum','decisions','increase','more']),
  q('housing-supply','Has housing supply fallen?',['are fewer homes being added','did housebuilding fall','are we building fewer houses'],'Net additional dwellings fell from 234,460 in 2021–22 to 208,600 in 2024–25; 2025–26 is unavailable.','This is the accepted England net-additions series.','It is not a live measure of construction starts or completions.',['story-housing-supply'],{display:'208,600',label:'net additional dwellings',period:'2024–25'},story('housing','2024-25','housing-net-additions'),['housing','supply','fall','homes','added']),
  q('affordability','Is housing becoming more affordable?',['house price to earnings','housing affordability improving','are house prices more affordable'],'The England house-price-to-earnings ratio improved from 9.06× to 7.64× in the displayed series, but remained high.','A lower ratio means prices were lower relative to annual workplace earnings.','The median ratio does not describe every place or household.',['story-housing-affordability'],{display:'7.64×',label:'annual workplace earnings',period:'2025'},story('housing','2025-26','housing-affordability'),['housing','affordable','affordability','earnings','price']),
  q('housing','How many households are in temporary accommodation?',['households in temporary accommodation','how much temporary accommodation','what about homelessness'],'135,580 households were in temporary accommodation in England at 31 March 2026.','This is a point-in-time household count.','It is not the number of people or the annual flow through homelessness services.',['story-housing-temporary-accommodation'],{display:'135,580',label:'households in temporary accommodation',period:'31 March 2026'},story('housing','2025-26','housing-temporary-accommodation'),['households','temporary','accommodation']),
  q('housing-spend-supply','Did housing spending rise while supply fell?',['housing spend rise supply fall','more housing spending fewer homes'],'Yes in the displayed comparison: UK housing-and-communities spending rose while England net additions fell.','The measures differ in geography and describe fiscal context versus output.','Observed co-movement is not proof that spending caused the supply change.',['e-housing','story-housing-supply'],{display:'£22.5bn',label:'housing and communities spending',period:'2025–26'},story('housing','2025-26','housing-spend','housing-net-additions'),['housing','spend','rise','supply','fall']),
  q('tax-gap','How large is the tax gap?',['how much tax goes uncollected','unpaid tax','how much tax doesnt get paid'],'The estimated UK tax gap was £59.2bn in 2024–25.','HMRC estimates this as 6.4% of theoretical tax liabilities.','It is not tax evasion alone or a sum that can all be collected.',['launch-tax-gap'],{display:'£59.2bn',label:'estimated tax gap',period:'2024–25'},value('launch-tax-gap','2024-25'),['tax','gap','uncollected','unpaid']),
  q('benefit-error','How much is lost through benefit fraud and error?',['benefits overpaid or lost','benefit overpayment','how much do we lose to benefits fraud'],'Benefits were overpaid by an estimated £9.9bn in FYE 2026.','The total includes fraud, claimant error and official error.','Not every overpayment was claimant fraud, deliberate or recoverable.',['launch-benefit-error'],{display:'£9.9bn',label:'benefit overpayments',period:'FYE 2026'},value('launch-benefit-error','2025-26'),['benefit','benefits','fraud','error','overpaid','lost','lose']),
  q('productivity','Is public-service productivity improving?',['public service productivity','is productivity rising','are public services getting more efficient'],'ONS estimates public-service productivity rose 0.9% in 2025, while remaining 2.5% below 2019.','ONS classifies the aggregate as statistics in development.','It does not establish cash savings or show that every service improved.',['launch-productivity'],{display:'+0.9%',label:'public-service productivity',period:'calendar 2025'},value('launch-productivity','2025-26'),['public','service','services','productivity','improve','rise','efficient']),
];
export const askSuggestions=['Did Labour inherit falling immigration?','Is the NHS waiting list falling?','How large is the tax gap?','How many households are in temporary accommodation?'];
const normalise=(input:string)=>input.toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9£]+/g,' ').trim();
const stop=new Set(['a','an','are','as','at','be','did','do','does','how','i','in','is','it','of','on','the','to','was','were','what','when','where']);
const tokens=(input:string)=>normalise(input).split(' ').filter(token=>token&&!stop.has(token));
export function matchSupportedQuestion(question:string):{question:SupportedQuestion;score:number}|undefined{
  const input=normalise(question);if(!input||/\b(vote|best party|good or bad|should|2030|forecast)\b/.test(input))return;
  const inputTokens=new Set(tokens(input));let best:{question:SupportedQuestion;score:number}|undefined;
  for(const item of supportedQuestions){const canonical=normalise(item.canonical),aliases=item.aliases.map(normalise);let score=input===canonical?100:aliases.includes(input)?95:0;if(!score){const keywordHits=item.keywords.filter(word=>inputTokens.has(normalise(word))).length;const phraseBonus=aliases.some(alias=>input.includes(alias)||alias.includes(input))?35:0;score=keywordHits*14+phraseBonus;}if(score>=28&&(!best||score>best.score||(score===best.score&&item.id.localeCompare(best.question.id)<0)))best={question:item,score};}
  return best;
}
export function answerQuestion(question:string):AskAnswer|undefined{const match=matchSupportedQuestion(question);if(!match)return;const item=match.question;return{title:item.canonical,answer:item.answer,keyEvidence:item.keyEvidence,score:match.score,claim:{id:item.id,claim:item.answer,botwReading:item.reading,doesNotProve:item.limit,evidenceIds:item.evidenceIds,focusTarget:item.focusTarget},suggestions:askSuggestions.filter(suggestion=>suggestion!==item.canonical).slice(0,3)}}
