import {useState} from 'react';
import {answerQuestion,askSuggestions,claims,journeys,type FocusTarget} from '../launch/explore';

export function AskBritain({openEvidence,showOnWall}:{openEvidence:(id:string)=>void;showOnWall:(target:FocusTarget)=>void}){
  const initial=new URL(location.href).searchParams.get('q')??'';const[question,setQuestion]=useState(initial),[submitted,setSubmitted]=useState(initial);const answer=answerQuestion(submitted);
  const submit=(value=question)=>{setQuestion(value);setSubmitted(value);const url=new URL(location.href);url.searchParams.set('view','ask');if(value)url.searchParams.set('q',value);else url.searchParams.delete('q');history.replaceState(null,'',url)};
  return <main className="ask-view"><header><small>03 · ASK THE WALL</small><h1>Ask Britain</h1><p>A bounded question router: verified answers where BOTW has evidence, an honest stop where it does not.</p></header><form onSubmit={event=>{event.preventDefault();submit()}}><label htmlFor="ask-input">What do you want to understand?</label><div><input id="ask-input" value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Try: How large is the tax gap?"/><button>ASK</button></div></form>{submitted&&(answer?<section className="ask-answer" aria-live="polite"><small>SUPPORTED QUESTION</small><h2>{answer.title}</h2><strong>{answer.answer}</strong><p>{answer.claim.botwReading}</p><p><b>What this does not prove:</b> {answer.claim.doesNotProve}</p><div><button onClick={()=>openEvidence(answer.claim.evidenceIds[0])}>VIEW EVIDENCE</button><button onClick={()=>showOnWall(answer.claim.focusTarget)}>SHOW ME ON THE WALL</button></div></section>:<section className="ask-answer unsupported" aria-live="polite"><small>OUTSIDE CURRENT COVERAGE</small><h2>BOTW cannot answer that yet.</h2><p>It only answers supported questions with mapped evidence. Try one of these:</p>{askSuggestions.map(item=><button key={item} onClick={()=>submit(item)}>{item}</button>)}</section>)}<section className="journey-links"><header><small>GUIDED QUESTIONS</small><h2>Follow the evidence, one step at a time</h2></header>{Object.values(journeys).map(journey=><a key={journey.id} href={`/?view=ask&journey=${journey.id}&step=1`}><b>{journey.title}</b><span>{journey.steps.length} evidence-backed steps →</span></a>)}</section><section className="claims"><header><small>CLAIM → EVIDENCE</small><h2>Five claims you can check</h2></header>{claims.map(claim=><article key={claim.id}><small>CLAIM</small><h3>{claim.claim}</h3><h4>BOTW READING</h4><p>{claim.botwReading}</p><h4>WHAT THIS DOES NOT PROVE</h4><p>{claim.doesNotProve}</p><div><button onClick={()=>openEvidence(claim.evidenceIds[0])}>EVIDENCE</button><button onClick={()=>showOnWall(claim.focusTarget)}>ON THE WALL</button></div></article>)}</section><section className="trust"><small>HOW BOTW WORKS</small><h2>Built to show its workings</h2><div>{['Official sources first','Every headline resolves to evidence','Periods and geographies stay visible','Money and operational measures stay distinct','Revisions are disclosed','Estimates are labelled','Unknowns remain unknown','Chronology is not causation','Deterministic answers only','No forecasts, scores or generated claims'].map((item,index)=><p key={item}><b>{String(index+1).padStart(2,'0')}</b>{item}</p>)}</div></section></main>;
}

export function GuidedJourney({id,openEvidence,showOnWall}:{id:'immigration'|'health';openEvidence:(id:string)=>void;showOnWall:(target:FocusTarget)=>void}){const journey=journeys[id],raw=Number(new URL(location.href).searchParams.get('step')??1),initial=Math.max(0,Math.min(journey.steps.length-1,raw-1)),[index,setIndex]=useState(initial),step=journey.steps[index];const go=(next:number)=>{setIndex(next);const url=new URL(location.href);url.searchParams.set('view','ask');url.searchParams.set('journey',id);url.searchParams.set('step',String(next+1));history.replaceState(null,'',url)};return <main className="guided-view"><a href="/?view=ask">← ASK BRITAIN</a><header><small>GUIDED JOURNEY · {index+1} OF {journey.steps.length}</small><h1>{journey.title}</h1><p>{journey.question}</p></header><nav aria-label="Journey progress">{journey.steps.map((_,i)=><button key={i} aria-label={`Go to step ${i+1}`} aria-current={i===index?'step':undefined} onClick={()=>go(i)}>{i+1}</button>)}</nav><article><small>{step.eyebrow}</small><h2>{step.title}</h2><strong>{step.value}</strong><p>{step.explanation}</p><aside><b>WHAT THIS CANNOT PROVE</b>{step.limit}</aside><div><button onClick={()=>openEvidence(step.evidenceIds[0])}>VIEW EVIDENCE</button><button onClick={()=>showOnWall(step.focusTarget)}>SHOW ME ON THE WALL</button></div></article><footer><button disabled={index===0} onClick={()=>go(index-1)}>← PREVIOUS</button><button disabled={index===journey.steps.length-1} onClick={()=>go(index+1)}>NEXT →</button></footer></main>}
