import {displayPeriod,realYears,type RealYear} from '../data/real/adapter';
import {healthStoryContextForYear,type HealthStoryContext} from '../data/real/healthStory';
import {housingStoryContextForYear,type HousingStoryContext} from '../data/real/housingStory';
import {storyContextForYear,type YearMetricView,type YearStoryContext} from '../data/real/story';
import type {Year} from '../types';

export type StoryId='immigration'|'health'|'housing';
const compact=(value:number,unit:string)=>unit==='percent'?`${value.toFixed(1)}%`:unit==='ratio'?`${value.toFixed(2)}×`:unit==='FTE'?`${(value/1e6).toFixed(3)}m FTE`:unit==='pathways'?`${(value/1e6).toFixed(3)}m`:value.toLocaleString();
const metricRow=(metric:YearMetricView,label?:string)=><div className="metric-row" key={label??metric.label}><dt>{(label??metric.label).toUpperCase()}</dt><dd><b>{metric.value===undefined?'NOT YET AVAILABLE':compact(metric.value,metric.unit)}</b><small>{metric.period} · {metric.classification} · {metric.comparability.toUpperCase()}</small></dd></div>;

function ImmigrationStory({year,setYear,openEvidence}:{year:Year;setYear:(year:Year)=>void;openEvidence:(id:string)=>void}){
  const contexts=realYears.map(item=>storyContextForYear(item)),selected=storyContextForYear(year);
  return <><div className="year-matrix" aria-label="Immigration five-year chronology">{contexts.map(context=>{const policy=context.events.filter(event=>event.track==='policy');return <article key={context.year} className={context.year===year?'selected':''}><button className="matrix-year" onClick={()=>setYear(context.year as RealYear)} aria-label={`View ${displayPeriod(context.year)} in chronology`} aria-pressed={context.year===year}>{displayPeriod(context.year)}</button><dl><div><dt>GOVERNMENT</dt><dd>{context.government}{context.handover&&<small>Handover: {context.handover}</small>}</dd></div><div><dt>KEY POLICY</dt><dd>{policy.length?policy.map(event=><button key={event.id} onClick={()=>openEvidence(event.sourceIds[0])}>{event.title}<small>{event.date} · policy owner recorded</small></button>):<span>No selected material event</span>}</dd></div>{metricRow(context.metric,'Net migration')}{context.operational.map(metric=>metricRow(metric))}</dl></article>})}</div><ImmigrationSummary selected={selected} openEvidence={openEvidence}/></>;
}

function ImmigrationSummary({selected,openEvidence}:{selected:YearStoryContext;openEvidence:(id:string)=>void}){return <aside className="evidence-summary"><b>SYSTEM STATE</b><dl><div><dt>DEMAND / VOLUME</dt><dd>{selected.metric.value!==undefined?`${selected.metric.value.toLocaleString()}k · ${selected.metric.period}`:selected.metric.period} · {selected.metric.classification}</dd></div><div><dt>SYSTEM CAPACITY</dt><dd>{selected.operational[1].value?.toLocaleString()} substantive initial decisions · {selected.operational[1].classification}</dd></div><div><dt>BACKLOG</dt><dd>{selected.operational[0].value?.toLocaleString()} people · {selected.operational[0].classification}</dd></div><div><dt>GOVERNMENT CONTEXT</dt><dd>{selected.government}{selected.handover?` · handover ${selected.handover}`:''}</dd></div><div><dt>AT / AFTER HANDOVER</dt><dd>{selected.inherited} {selected.after}</dd></div><div><dt>LIMIT</dt><dd>Timing alone cannot assign movement to one policy, party or prime minister.</dd></div></dl><button onClick={()=>openEvidence('story-asylum-awaiting')}>Inspect Home Office system evidence ↗</button></aside>}

function HealthStory({year,setYear,openEvidence}:{year:Year;setYear:(year:Year)=>void;openEvidence:(id:string)=>void}){const contexts=realYears.map(item=>healthStoryContextForYear(item)),selected=healthStoryContextForYear(year);return <><div className="year-matrix health-matrix" aria-label="Health five-year chronology">{contexts.map(context=>{const policy=context.events.filter(event=>event.track==='policy');return <article key={context.year} className={context.year===year?'selected':''}><button className="matrix-year" onClick={()=>setYear(context.year as RealYear)} aria-label={`View ${displayPeriod(context.year)} in Health chronology`} aria-pressed={context.year===year}>{displayPeriod(context.year)}</button><dl><div><dt>GOVERNMENT</dt><dd>{context.government}{context.handover&&<small>Handover: {context.handover}</small>}</dd></div><div><dt>POLICY CONTEXT</dt><dd>{policy.length?policy.map(event=><button key={event.id} onClick={()=>openEvidence(event.sourceIds[0])}>{event.title}<small>{event.date} · documented policy</small></button>):<span>No selected material event</span>}</dd></div><div className="metric-row"><dt>UK HEALTH SPEND</dt><dd><b>£{context.spend.value.toFixed(1)}bn · {context.spend.share.toFixed(1)}%</b><small>Nominal {context.spend.cashDirection.toUpperCase()} · share {context.spend.shareDirection.toUpperCase()}</small></dd></div>{metricRow(context.operational[0],'Capacity · workforce')}{metricRow(context.operational[1],'Activity · completed')}{metricRow(context.metric,'Outcome · waiting')}{metricRow(context.operational[2],'Outcome · within 18 weeks')}</dl></article>})}</div><HealthSummary selected={selected} openEvidence={openEvidence}/></>}

function HealthSummary({selected,openEvidence}:{selected:HealthStoryContext;openEvidence:(id:string)=>void}){return <aside className="evidence-summary health-summary"><b>HEALTH SYSTEM STATE</b><small className="geo-label">ENGLAND OPERATIONAL MEASURE · UK SPEND</small><dl><div><dt>MONEY</dt><dd>£{selected.spend.value.toFixed(1)}bn nominal · {selected.spend.share.toFixed(1)}% of public money</dd></div><div><dt>CAPACITY</dt><dd>{compact(selected.operational[0].value!,selected.operational[0].unit)} · {selected.operational[0].classification}</dd></div><div><dt>OUTPUT</dt><dd>{compact(selected.operational[1].value!,selected.operational[1].unit)} March pathways · {selected.operational[1].classification}</dd></div><div><dt>OUTCOME</dt><dd>{compact(selected.metric.value!,selected.metric.unit)} waiting · {compact(selected.operational[2].value!,selected.operational[2].unit)} within 18 weeks</dd></div><div><dt>GOVERNMENT</dt><dd>{selected.government}{selected.handover?` · handover ${selected.handover}`:''}</dd></div><div><dt>AT / AFTER HANDOVER</dt><dd>{selected.inherited} {selected.after}</dd></div></dl>{selected.contradictions.map(label=><p className="contradiction" key={label}><strong>{label}</strong><br/>Observed co-movement; not proof that spending or capacity caused the outcome.</p>)}<p><strong>LIMIT</strong> Spend is UK-wide; operational measures are England-only. Pathways are not people. March 2024 has a documented scope break.</p><button onClick={()=>openEvidence('story-health-rtt')}>Inspect NHS England system evidence ↗</button></aside>}

function HousingStory({year,setYear,openEvidence}:{year:Year;setYear:(year:Year)=>void;openEvidence:(id:string)=>void}){const contexts=realYears.map(item=>housingStoryContextForYear(item)),selected=housingStoryContextForYear(year);return <><div className="year-matrix housing-matrix" aria-label="Housing five-year chronology">{contexts.map(context=>{const policy=context.events.filter(event=>event.track==='policy');return <article key={context.year} className={context.year===year?'selected':''}><button className="matrix-year" onClick={()=>setYear(context.year as RealYear)} aria-label={`View ${displayPeriod(context.year)} in Housing chronology`} aria-pressed={context.year===year}>{displayPeriod(context.year)}</button><dl><div><dt>GOVERNMENT</dt><dd>{context.government}{context.handover&&<small>Handover: {context.handover}</small>}</dd></div><div><dt>POLICY</dt><dd>{policy.length?policy.map(event=><button key={event.id} onClick={()=>openEvidence(event.sourceIds[0])}>{event.title}<small>{event.date} · {event.policyOwner} · {event.policyStatus}<br/>Relationship: {event.relationship} · expected lag: {event.expectedLag}</small></button>):<span>No selected material event</span>}</dd></div><div className="metric-row"><dt>UK PUBLIC SPEND</dt><dd><b>£{context.spend.value.toFixed(1)}bn · £{context.spend.share.toFixed(2)} of £100</b><small>Previous: {context.spend.cashChange>=0?'+':''}{context.spend.cashChange.toFixed(1)}bn · since 2021–22: {context.spend.baseCashChange>=0?'+':''}{context.spend.baseCashChange.toFixed(1)}bn · context only</small></dd></div>{metricRow(context.supply,'Supply · net additions')}{metricRow(context.affordability,'Affordability · price/earnings')}{metricRow(context.housingNeed,'Housing need · temporary accommodation')}</dl></article>})}</div><HousingSummary selected={selected} openEvidence={openEvidence}/></>}

function HousingSummary({selected,openEvidence}:{selected:HousingStoryContext;openEvidence:(id:string)=>void}){const policy=selected.events.filter(event=>event.track==='policy');return <aside className="evidence-summary housing-summary"><b>HOUSING SYSTEM STATE</b><small className="geo-label">ENGLAND SYSTEM MEASURE · UK PUBLIC SPEND</small><dl><div><dt>MONEY</dt><dd>£{selected.spend.value.toFixed(1)}bn nominal · £{selected.spend.share.toFixed(2)} of every £100 · spending context, not performance</dd></div><div><dt>SUPPLY · OUTPUT</dt><dd>{selected.supply.value===undefined?'Annual result not yet available':`${compact(selected.supply.value,selected.supply.unit)} · ${selected.supply.classification}`}</dd></div><div><dt>AFFORDABILITY · OUTCOME</dt><dd>{compact(selected.affordability.value!,selected.affordability.unit)} median price/earnings · {selected.affordability.classification}</dd></div><div><dt>SOCIAL OUTCOME</dt><dd>{compact(selected.housingNeed.value!,selected.housingNeed.unit)} households in temporary accommodation · {selected.housingNeed.classification}</dd></div><div><dt>POLICY</dt><dd>{policy.length?policy.map(event=>`${event.title} · ${event.expectedLag} lag`).join('; '):'No selected material event'}</dd></div><div><dt>INHERITED / AFTER</dt><dd>{selected.inherited} {selected.after}</dd></div><div><dt>MACRO CONTEXT</dt><dd>House prices and mortgage rates are not scored as government performance; no extra macro series is shown.</dd></div><div><dt>WHAT EVIDENCE CANNOT SAY</dt><dd>Co-movement cannot prove spending or one government policy caused supply, affordability or homelessness movement. No migration-to-housing claim is made.</dd></div></dl>{selected.contradictions.map(label=><p className="contradiction" key={label}><strong>{label}</strong><br/>Observed co-movement only; not proof that spending caused supply or that supply alone caused the outcome.</p>)}<p><strong>LAG WARNING</strong> Planning and affordable-housing programmes can take years to affect completions. Annual and fiscal observations straddling 5 July 2024 are not Labour performance scores.</p><button onClick={()=>openEvidence('story-housing-supply')}>Inspect official housing-system evidence ↗</button></aside>}

export function HowWeGotHere({year,setYear,openEvidence,story,setStory}:{year:Year;setYear:(year:Year)=>void;openEvidence:(id:string)=>void;story:StoryId;setStory:(story:StoryId)=>void}){const label=story==='health'?'Health':story==='housing'?'Housing':'Immigration';return <section className="story-chronology" aria-label={`How We Got Here — ${label}`}><header><div><small>HOW WE GOT HERE</small><h2>{label}</h2><span>Government, policy, money, system performance and outcome dates stay separate. Chronology is not causation.</span></div><div className="topic-selector" role="group" aria-label="Story"><button className={story==='immigration'?'active':''} onClick={()=>setStory('immigration')} aria-pressed={story==='immigration'}>IMMIGRATION</button><button className={story==='health'?'active':''} onClick={()=>setStory('health')} aria-pressed={story==='health'}>HEALTH</button><button className={story==='housing'?'active':''} onClick={()=>setStory('housing')} aria-pressed={story==='housing'}>HOUSING</button></div></header><div className="story-body">{story==='health'?<HealthStory year={year} setYear={setYear} openEvidence={openEvidence}/>:story==='housing'?<HousingStory year={year} setYear={setYear} openEvidence={openEvidence}/>:<ImmigrationStory year={year} setYear={setYear} openEvidence={openEvidence}/>}</div></section>}
