import {displayPeriod,realYears,type RealYear} from '../data/real/adapter';
import {healthStoryContextForYear,type HealthStoryContext} from '../data/real/healthStory';
import {storyContextForYear,type YearMetricView,type YearStoryContext} from '../data/real/story';
import type {Year} from '../types';

export type StoryId='immigration'|'health';
const compact=(value:number,unit:string)=>unit==='percent'?`${value.toFixed(1)}%`:unit==='FTE'?`${(value/1e6).toFixed(3)}m FTE`:unit==='pathways'?`${(value/1e6).toFixed(3)}m`:value.toLocaleString();
const metricRow=(metric:YearMetricView,label?:string)=><div className="metric-row" key={label??metric.label}><dt>{(label??metric.label).toUpperCase()}</dt><dd><b>{metric.value===undefined?metric.classification:compact(metric.value,metric.unit)}</b><small>{metric.period} · {metric.classification} · {metric.comparability.toUpperCase()}</small></dd></div>;

function ImmigrationStory({year,setYear,openEvidence}:{year:Year;setYear:(year:Year)=>void;openEvidence:(id:string)=>void}){
  const contexts=realYears.map(item=>storyContextForYear(item)),selected=storyContextForYear(year);
  return <><div className="year-matrix" aria-label="Immigration five-year chronology">{contexts.map(context=>{const policy=context.events.filter(event=>event.track==='policy');return <article key={context.year} className={context.year===year?'selected':''}><button className="matrix-year" onClick={()=>setYear(context.year as RealYear)} aria-label={`View ${displayPeriod(context.year)} in chronology`} aria-pressed={context.year===year}>{displayPeriod(context.year)}</button><dl><div><dt>GOVERNMENT</dt><dd>{context.government}{context.handover&&<small>Handover: {context.handover}</small>}</dd></div><div><dt>KEY POLICY</dt><dd>{policy.length?policy.map(event=><button key={event.id} onClick={()=>openEvidence(event.sourceIds[0])}>{event.title}<small>{event.date} · policy owner recorded</small></button>):<span>No selected material event</span>}</dd></div>{metricRow(context.metric,'Net migration')}{context.operational.map(metric=>metricRow(metric))}</dl></article>})}</div><ImmigrationSummary selected={selected} openEvidence={openEvidence}/></>;
}

function ImmigrationSummary({selected,openEvidence}:{selected:YearStoryContext;openEvidence:(id:string)=>void}){return <aside className="evidence-summary"><b>SYSTEM STATE</b><dl><div><dt>DEMAND / VOLUME</dt><dd>{selected.metric.value!==undefined?`${selected.metric.value.toLocaleString()}k · ${selected.metric.period}`:selected.metric.period} · {selected.metric.classification}</dd></div><div><dt>SYSTEM CAPACITY</dt><dd>{selected.operational[1].value?.toLocaleString()} substantive initial decisions · {selected.operational[1].classification}</dd></div><div><dt>BACKLOG</dt><dd>{selected.operational[0].value?.toLocaleString()} people · {selected.operational[0].classification}</dd></div><div><dt>GOVERNMENT CONTEXT</dt><dd>{selected.government}{selected.handover?` · handover ${selected.handover}`:''}</dd></div><div><dt>AT / AFTER HANDOVER</dt><dd>{selected.inherited} {selected.after}</dd></div><div><dt>LIMIT</dt><dd>Timing alone cannot assign movement to one policy, party or prime minister.</dd></div></dl><button onClick={()=>openEvidence('story-asylum-awaiting')}>Inspect Home Office system evidence ↗</button></aside>}

function HealthStory({year,setYear,openEvidence}:{year:Year;setYear:(year:Year)=>void;openEvidence:(id:string)=>void}){const contexts=realYears.map(item=>healthStoryContextForYear(item)),selected=healthStoryContextForYear(year);return <><div className="year-matrix health-matrix" aria-label="Health five-year chronology">{contexts.map(context=>{const policy=context.events.filter(event=>event.track==='policy');return <article key={context.year} className={context.year===year?'selected':''}><button className="matrix-year" onClick={()=>setYear(context.year as RealYear)} aria-label={`View ${displayPeriod(context.year)} in Health chronology`} aria-pressed={context.year===year}>{displayPeriod(context.year)}</button><dl><div><dt>GOVERNMENT</dt><dd>{context.government}{context.handover&&<small>Handover: {context.handover}</small>}</dd></div><div><dt>POLICY CONTEXT</dt><dd>{policy.length?policy.map(event=><button key={event.id} onClick={()=>openEvidence(event.sourceIds[0])}>{event.title}<small>{event.date} · documented policy</small></button>):<span>No selected material event</span>}</dd></div><div className="metric-row"><dt>UK HEALTH SPEND</dt><dd><b>£{context.spend.value.toFixed(1)}bn · {context.spend.share.toFixed(1)}%</b><small>Nominal {context.spend.cashDirection.toUpperCase()} · share {context.spend.shareDirection.toUpperCase()}</small></dd></div>{metricRow(context.operational[0],'Capacity · workforce')}{metricRow(context.operational[1],'Activity · completed')}{metricRow(context.metric,'Outcome · waiting')}{metricRow(context.operational[2],'Outcome · within 18 weeks')}</dl></article>})}</div><HealthSummary selected={selected} openEvidence={openEvidence}/></>}

function HealthSummary({selected,openEvidence}:{selected:HealthStoryContext;openEvidence:(id:string)=>void}){return <aside className="evidence-summary health-summary"><b>HEALTH SYSTEM STATE</b><small className="geo-label">ENGLAND OPERATIONAL MEASURE · UK SPEND</small><dl><div><dt>MONEY</dt><dd>£{selected.spend.value.toFixed(1)}bn nominal · {selected.spend.share.toFixed(1)}% of public money</dd></div><div><dt>CAPACITY</dt><dd>{compact(selected.operational[0].value!,selected.operational[0].unit)} · {selected.operational[0].classification}</dd></div><div><dt>OUTPUT</dt><dd>{compact(selected.operational[1].value!,selected.operational[1].unit)} March pathways · {selected.operational[1].classification}</dd></div><div><dt>OUTCOME</dt><dd>{compact(selected.metric.value!,selected.metric.unit)} waiting · {compact(selected.operational[2].value!,selected.operational[2].unit)} within 18 weeks</dd></div><div><dt>GOVERNMENT</dt><dd>{selected.government}{selected.handover?` · handover ${selected.handover}`:''}</dd></div><div><dt>AT / AFTER HANDOVER</dt><dd>{selected.inherited} {selected.after}</dd></div></dl>{selected.contradictions.map(label=><p className="contradiction" key={label}><strong>{label}</strong><br/>Observed co-movement; not proof that spending or capacity caused the outcome.</p>)}<p><strong>LIMIT</strong> Spend is UK-wide; operational measures are England-only. Pathways are not people. March 2024 has a documented scope break.</p><button onClick={()=>openEvidence('story-health-rtt')}>Inspect NHS England system evidence ↗</button></aside>}

export function HowWeGotHere({year,setYear,openEvidence,story,setStory}:{year:Year;setYear:(year:Year)=>void;openEvidence:(id:string)=>void;story:StoryId;setStory:(story:StoryId)=>void}){return <section className="story-chronology" aria-label={`How We Got Here — ${story==='health'?'Health':'Immigration'}`}><header><div><small>HOW WE GOT HERE</small><h2>{story==='health'?'Health':'Immigration'}</h2><span>Government, policy, money, system performance and outcome dates stay separate. Chronology is not causation.</span></div><div className="topic-selector" role="group" aria-label="Story"><button className={story==='immigration'?'active':''} onClick={()=>setStory('immigration')} aria-pressed={story==='immigration'}>IMMIGRATION</button><button className={story==='health'?'active':''} onClick={()=>setStory('health')} aria-pressed={story==='health'}>HEALTH</button></div></header><div className="story-body">{story==='health'?<HealthStory year={year} setYear={setYear} openEvidence={openEvidence}/>:<ImmigrationStory year={year} setYear={setYear} openEvidence={openEvidence}/>}</div></section>}
