import {useEffect,useMemo,useRef,useState} from 'react';
import {BadgePoundSterling,Building2,BusFront,Calculator,Castle,Factory,GraduationCap,HandCoins,HeartPulse,Home,Landmark,Leaf,Library,ReceiptText,Scale,Shield,ShoppingBag,Users,WalletCards,type LucideIcon} from 'lucide-react';
import {wallData,totalFunding} from '../data';
import {displayPeriod,realYears,type RealYear} from '../data/real/adapter';
import {HowWeGotHere,type StoryId} from './HowWeGotHere';
import {MoneyDisplay} from './MoneyDisplay';
import type {Year} from '../types';

type Unit='hundred'|'bn';
export type WallFocus={topicId?:StoryId;periodId?:string;metricIds?:string[];source?:'what-changed'|'manual'};
type Props={year:Year;setYear:(year:Year)=>void;unit:Unit;setUnit:(unit:Unit)=>void;openEvidence:(id:string)=>void;story:StoryId;setStory:(story:StoryId)=>void;focus?:WallFocus};
type FiscalItem={id:string;name:string;value:number;previousValue:number;baseValue:number;evidenceId:string;technical?:boolean;borrowing?:boolean};

const tones=['#477f9f','#4f8a8d','#74955e','#a18e4f','#76698c','#897c9b','#a76058','#b47755','#ad874e','#a08d55','#56878a','#5d8198','#7b7090','#6e8760','#57878b','#71808a','#92989b'];
const perHundred=(value:number,total:number)=>(value/total*100).toFixed(1);
const direction=(value:number)=>value>.049?'up':value<-.049?'down':'unchanged';
const changeValue=(value:number,suffix:string)=>Math.abs(value)<.05?'less than 0.1'+suffix:`${Math.abs(value).toFixed(1)}${suffix}`;
const sourceOrder=['income','business','consumer','capital','other-income','borrowing'];
const destinationOrder=['health','welfare','pensions','interest','education','defence','transport','justice','housing','economy','environment','culture','admin','technical'];
const fiscalIcons:Record<string,LucideIcon>={income:Users,business:Building2,consumer:ShoppingBag,capital:Home,'other-income':ReceiptText,borrowing:WalletCards,health:HeartPulse,welfare:HandCoins,pensions:Users,interest:BadgePoundSterling,education:GraduationCap,defence:Shield,transport:BusFront,justice:Scale,housing:Home,economy:Factory,environment:Leaf,culture:Library,admin:Landmark,technical:Calculator};

function UnitTokens({share,tone='standard',colour,major}:{share:number;tone?:'standard'|'borrowing'|'technical';colour?:string;major:boolean}){
  return <div className={`proportion-strip ${tone} ${major?'major-strip':''}`} style={{'--token-colour':colour} as React.CSSProperties} aria-label={`${share.toFixed(1)} pounds out of every one hundred`}><i style={{width:`${Math.min(100,share)}%`}}/></div>;
}

function FiscalRow({item,total,previousTotal,baseTotal,unit,flowDirection,rank,major,hasPrior,previousPeriod,active,setActive,selectActive,openEvidence}:{item:FiscalItem;total:number;previousTotal:number;baseTotal:number;unit:Unit;flowDirection:'in'|'out';rank:number;major:boolean;hasPrior:boolean;previousPeriod:string;active:boolean;setActive:(active:boolean)=>void;selectActive:()=>void;openEvidence:(id:string)=>void}){
  const Icon=fiscalIcons[item.id]??Castle;const share=item.value/total*100;const colour=item.borrowing?'#7253a0':item.technical?'#92999b':tones[flowDirection==='in'?rank:rank+6];
  const cashDelta=item.value-item.previousValue,cashPercentage=item.previousValue===0?undefined:cashDelta/item.previousValue*100,shareDelta=share-item.previousValue/previousTotal*100,baseCashDelta=item.value-item.baseValue,baseDelta=share-item.baseValue/baseTotal*100;
  const signed=(value:number,suffix:string)=>`${value>=0?'+':'−'}${Math.abs(value).toFixed(1)}${suffix}`;
  const comparison=`Previous: ${signed(cashDelta,'bn')}, ${signed(shareDelta,'pp')}. Since 2021–22: ${signed(baseCashDelta,'bn')}, ${signed(baseDelta,'pp')}.`;
  const cashDirection=cashPercentage===undefined?'unchanged':direction(cashPercentage),shareDirection=direction(shareDelta);const changeCopy=hasPrior&&cashPercentage!==undefined?`${cashDirection==='up'?'↑':cashDirection==='down'?'↓':'—'} ${changeValue(cashPercentage,'%')} cash · ${shareDirection==='up'?'↑':shareDirection==='down'?'↓':'—'} ${changeValue(shareDelta,'pp')} share`:'First comparable period';
  const ariaValue=unit==='hundred'?`${perHundred(item.value,total)} pounds of every one hundred`:`${item.value.toFixed(1)} billion pounds`;
  const ariaChange=hasPrior&&cashPercentage!==undefined?`${cashDirection} ${changeValue(cashPercentage,' percent')} from ${previousPeriod}, share ${shareDirection} ${changeValue(shareDelta,' percentage points')}`:'first comparable period; no prior comparison';
  return <button data-flow-key={`${flowDirection}:${item.id}`} style={{'--row-colour':colour} as React.CSSProperties} className={`fiscal-row ${flowDirection} ${major&&!item.technical?'major':''} ${active?'flow-active':''} ${item.borrowing?'borrowing':''} ${item.technical?'technical':''}`} onMouseEnter={()=>setActive(true)} onMouseLeave={()=>setActive(false)} onFocus={()=>setActive(true)} onBlur={()=>setActive(false)} onClick={()=>{selectActive();openEvidence(item.evidenceId)}} aria-label={`${item.name}, ${ariaValue}, ${share.toFixed(1)} percent of total, ${ariaChange}.`} title={`${comparison} Select for source and methodology.`}>
    <span className="row-icon" aria-hidden="true"><Icon/></span>
    <span className="row-copy"><strong>{item.name}</strong>{item.borrowing&&<small>Fills the gap between what we raise and what we spend · not revenue</small>}{item.technical&&<small>NOT A SERVICE</small>}</span>
    <UnitTokens share={share} colour={colour} tone={item.borrowing?'borrowing':item.technical?'technical':'standard'} major={major}/>
    <span className="row-number" title={comparison}><b>{unit==='hundred'?<><MoneyDisplay value={perHundred(item.value,total)}/><small>of every £100</small></>:<MoneyDisplay value={item.value.toFixed(1)} unit="bn"/>}</b><em>{share.toFixed(1)}% of total</em><small className="row-change">{changeCopy}{hasPrior&&<span> vs {previousPeriod}</span>}</small></span>
    <span className="expand" aria-hidden="true">＋</span>
  </button>;
}

export function NationalWall({year,setYear,unit,setUnit,openEvidence,story,setStory,focus}:Props){
  const[showHelp,setShowHelp]=useState(false),[hoverFlow,setHoverFlow]=useState<string>(),[selectedFlow,setSelectedFlow]=useState<string>();const activeFlow=hoverFlow??selectedFlow;const historyRef=useRef<HTMLElement>(null);const total=totalFunding(wallData,year);const yearIndex=realYears.indexOf(year as RealYear);const previousYear=realYears[Math.max(0,yearIndex-1)];const previousTotal=totalFunding(wallData,previousYear),baseTotal=totalFunding(wallData,2021);const previousPeriod=displayPeriod(previousYear),hasPrior=yearIndex>0;
  useEffect(()=>{if(focus?.source==='what-changed'){const section=historyRef.current;if(typeof section?.scrollIntoView==='function')section.scrollIntoView({behavior:'smooth',block:'start'});section?.focus({preventScroll:true})}},[focus]);
  const sources=useMemo(()=>wallData.funding.map(x=>({id:x.id,name:x.name,value:x.values[year],previousValue:x.values[previousYear],baseValue:x.values[2021],evidenceId:x.evidenceId,borrowing:x.borrowing})).sort((a,b)=>sourceOrder.indexOf(a.id)-sourceOrder.indexOf(b.id)),[year,previousYear]);
  const destinations=useMemo(()=>wallData.domains.filter(x=>x.values[year]>0).map(x=>({id:x.id,name:x.name,value:x.values[year],previousValue:x.values[previousYear],baseValue:x.values[2021],evidenceId:x.evidenceId,technical:x.id==='technical'})).sort((a,b)=>destinationOrder.indexOf(a.id)-destinationOrder.indexOf(b.id)),[year,previousYear]);
  const majorSources=new Set([...sources].sort((a,b)=>b.value-a.value).slice(0,3).map(item=>item.id)),majorDestinations=new Set([...destinations].filter(item=>!item.technical).sort((a,b)=>b.value-a.value).slice(0,3).map(item=>item.id));
  return <main className="national-wall">
    <header className="editorial-header"><div className="brand-lockup"><span className="chapter-label">01 · UNDERSTAND BRITAIN</span><a className="wordmark" href="/">BRITAIN ON THE WALL</a><p>Where Britain’s money comes from—and where it goes.</p><small>{displayPeriod(year)} · latest complete outturn · <button onClick={()=>openEvidence('e-income')}>Sources and method</button></small></div><div className="header-unit-toggle unit-toggle" role="group" aria-label="Display unit"><button className={unit==='hundred'?'active':''} aria-pressed={unit==='hundred'} onClick={()=>setUnit('hundred')}>EVERY £100</button><button className={unit==='bn'?'active':''} aria-pressed={unit==='bn'} onClick={()=>setUnit('bn')}>£ BILLIONS</button></div><div className="header-summary"><span><b>{total>=1000?<MoneyDisplay value={(total/1000).toFixed(3)} unit="tn"/>:<MoneyDisplay value={total.toFixed(1)} unit="bn"/>}</b><small>Total public money</small></span><span><b><MoneyDisplay value="100"/></b><small>Raised or borrowed</small></span><button onClick={()=>setShowHelp(!showHelp)} aria-expanded={showHelp}>How to read</button></div></header>
    {showHelp&&<aside className="read-note">Each proportional strip shows the category’s share of every £100. Values and ordering follow the selected period; borrowing remains separate from receipts.</aside>}
    <section className="money-stage">
      <svg className={`editorial-flows ${activeFlow?'has-active-flow':''}`} viewBox="0 0 1400 620" preserveAspectRatio="none" aria-hidden="true">{sources.map((item,i)=><path key={item.id} data-flow-id={item.id} className={`${item.borrowing?'borrow-flow ':''}${activeFlow===`in:${item.id}`?'active-flow':''}`} d={`M 465 ${88+i*81} C 535 ${88+i*81}, 550 ${310+(i-2.5)*18}, 638 310`} stroke={item.borrowing?'#7253a0':tones[i]} strokeWidth={Math.max(7,item.value/total*130)} />)}{destinations.map((item,i)=><path key={item.id} data-flow-id={item.id} className={`${item.technical?'technical-flow ':''}${activeFlow===`out:${item.id}`?'active-flow':''}`} d={`M 762 310 C 850 ${310+(i-6)*12}, 875 ${48+i*40}, 960 ${48+i*40}`} stroke={item.technical?'#92999b':tones[i+6]} strokeWidth={Math.max(5,item.value/total*95)} />)}</svg>
      <section className="fiscal-column sources"><div className="section-heading"><small>01 · MONEY IN</small><h1>Where Britain’s £100 comes from</h1></div>{sources.map((item,i)=><FiscalRow key={item.id} item={item} total={total} previousTotal={previousTotal} baseTotal={baseTotal} unit={unit} flowDirection="in" rank={i} major={majorSources.has(item.id)} hasPrior={hasPrior} previousPeriod={previousPeriod} active={activeFlow===`in:${item.id}`} setActive={active=>setHoverFlow(active?`in:${item.id}`:undefined)} selectActive={()=>setSelectedFlow(`in:${item.id}`)} openEvidence={openEvidence}/>)}</section>
      <section className="pool-column"><div className="pool-label"><span>PUBLIC MONEY</span><strong><MoneyDisplay value="100"/></strong><em>of every £100</em><small>{total>=1000?<><MoneyDisplay value={(total/1000).toFixed(3)} unit="tn"/> in total</>:<><MoneyDisplay value={total.toFixed(1)} unit="bn"/> in total</>}</small></div><div className="pool-object"><div className="britain-mark">BRITAIN</div></div><p>Money in equals money out.<br/><small>Borrowing balances the gap.</small></p></section>
      <section className="fiscal-column destinations"><div className="section-heading"><small>02 · MONEY OUT</small><h1>Where Britain’s £100 goes</h1></div>{destinations.map((item,i)=><FiscalRow key={item.id} item={item} total={total} previousTotal={previousTotal} baseTotal={baseTotal} unit={unit} flowDirection="out" rank={i} major={majorDestinations.has(item.id)} hasPrior={hasPrior} previousPeriod={previousPeriod} active={activeFlow===`out:${item.id}`} setActive={active=>setHoverFlow(active?`out:${item.id}`:undefined)} selectActive={()=>setSelectedFlow(`out:${item.id}`)} openEvidence={openEvidence}/>)}</section>
    </section>
    <section className="lower-editorial" id="history" ref={historyRef} tabIndex={-1}><HowWeGotHere year={year} setYear={setYear} openEvidence={openEvidence} story={story} setStory={setStory} focus={focus}/></section><footer className="editorial-footer"><b>TRANSPARENT · EVIDENCE-BASED · INDEPENDENT</b><span>Official sources, visible definitions and explicit limits.</span></footer>
  </main>;
}
