import {wallData,totalFunding} from '../data';
import {displayPeriod} from '../data/real/adapter';
import {valueLeakageEvidenceById,valueLeakageMetrics as metrics} from '../data/real/valueLeakage';
import type {Year} from '../types';
import {MoneyDisplay} from './MoneyDisplay';

const Stat=({label,children,detail}:{label:string;children:React.ReactNode;detail?:string})=><div className="value-stat"><small>{label}</small><strong>{children}</strong>{detail&&<span>{detail}</span>}</div>;
const Boundaries=({evidenceId}:{evidenceId:string})=>{const item=valueLeakageEvidenceById(evidenceId);return item?<dl className="value-boundaries"><div><dt>WHAT IT MEASURES</dt><dd>{item.definition}</dd></div><div><dt>PERIOD · GEOGRAPHY · STATUS</dt><dd>{item.period} · {item.geography} · {item.statusLabel??item.dataStatus}</dd></div><div><dt>WHAT IT CANNOT PROVE</dt><dd>{item.cannotProve??item.limitations}</dd></div></dl>:null};
export function ValueLeakage({year,openEvidence,focusedMetricId}:{year:Year;openEvidence:(id:string)=>void;focusedMetricId?:string}){
  const index=wallData.years.indexOf(year),previous=wallData.years[Math.max(0,index-1)],interest=wallData.domains.find(item=>item.id==='interest')!,current=interest.values[year],previousValue=interest.values[previous],base=interest.values[2021],total=totalFunding(wallData,year);
  return <section className={`value-leakage ${focusedMetricId?'wall-focused':''}`} data-focused-metric={focusedMetricId} id="value-leakage" aria-labelledby="value-leakage-title"><header><span className="chapter-label">03 · FOLLOW THE VALUE</span><h2 id="value-leakage-title">WHERE VALUE IS LOST OR CONSTRAINED</h2><p>Four national measures that put value for money and measurable leakage in context. None is proof of waste.</p></header><div className="value-grid">
    <article><div className="value-card-head"><span>PUBLIC-SERVICE PRODUCTIVITY</span><button onClick={()=>openEvidence(metrics.productivity.evidenceId)}>Evidence</button></div><h3>Are services producing more for the resources going in?</h3><div className="value-stats three"><Stat label="INPUTS"><>{`↑ ${metrics.productivity.inputsGrowth.toFixed(1)}%`}</></Stat><Stat label="OUTPUTS"><>{`↑ ${metrics.productivity.outputGrowth.toFixed(1)}%`}</></Stat><Stat label="PRODUCTIVITY"><>{`↑ ${metrics.productivity.productivityGrowth.toFixed(1)}%`}</></Stat></div><b>{Math.abs(metrics.productivity.versus2019)}% below 2019</b><Boundaries evidenceId={metrics.productivity.evidenceId}/></article>
    <article><div className="value-card-head"><span>BENEFIT FRAUD &amp; ERROR</span><button onClick={()=>openEvidence(metrics.benefits.evidenceId)}>Evidence</button></div><h3>Benefit overpayments and underpayments</h3><div className="value-stats two"><Stat label="BENEFIT EXPENDITURE"><MoneyDisplay value={metrics.benefits.expenditure.toFixed(1)} unit="bn"/></Stat><Stat label="OVERPAID THROUGH FRAUD & ERROR"><MoneyDisplay value={metrics.benefits.overpayments.toFixed(1)} unit="bn"/> <em>{metrics.benefits.overpaymentRate}%</em></Stat><Stat label="NET LOSS AFTER INCLUDED RECOVERIES"><MoneyDisplay value={metrics.benefits.netLoss.toFixed(1)} unit="bn"/></Stat><Stat label="UNDERPAID"><MoneyDisplay value={metrics.benefits.underpayments.toFixed(1)} unit="bn"/></Stat></div><p>Overpayments include fraud, claimant error and official error; they are not all claimant fraud.</p><Boundaries evidenceId={metrics.benefits.evidenceId}/></article>
    <article><div className="value-card-head"><span>TAX GAP</span><button onClick={()=>openEvidence(metrics.taxGap.evidenceId)}>Evidence</button></div><h3>Estimated difference between tax due and paid</h3><div className="value-stats two"><Stat label="TAX DUE"><MoneyDisplay value={metrics.taxGap.theoreticalLiabilities.toFixed(1)} unit="bn"/></Stat><Stat label="ESTIMATED TAX GAP"><MoneyDisplay value={metrics.taxGap.gap.toFixed(1)} unit="bn"/> <em>{metrics.taxGap.gapRate}%</em></Stat></div><b>Largest customer group: {metrics.taxGap.largestContributor}</b><p>The tax gap includes several forms of non-compliance. It is not all evasion.</p><Boundaries evidenceId={metrics.taxGap.evidenceId}/></article>
    <article><div className="value-card-head"><span>DEBT INTEREST</span><button onClick={()=>openEvidence(interest.evidenceId)}>Evidence</button></div><h3>Cost of servicing government debt and related transactions</h3><div className="value-stats two"><Stat label="DEBT INTEREST & TRANSACTIONS"><MoneyDisplay value={current.toFixed(1)} unit="bn"/></Stat><Stat label="SHARE OF EVERY £100"><MoneyDisplay value={(current/total*100).toFixed(1)}/></Stat></div><b>{index?`${current>=previousValue?'↑':'↓'} ${Math.abs((current-previousValue)/previousValue*100).toFixed(1)}% vs ${displayPeriod(previous)}`:'First comparable period'} · {current>=base?'↑':'↓'} <MoneyDisplay value={Math.abs(current-base).toFixed(1)} unit="bn"/> since 2021–22</b><dl className="value-boundaries"><div><dt>WHAT IT MEASURES</dt><dd>Government debt-interest costs and related public-sector transactions in the selected fiscal period.</dd></div><div><dt>PERIOD · GEOGRAPHY · STATUS</dt><dd>{displayPeriod(year)} · United Kingdom public sector · official outturn</dd></div><div><dt>WHAT IT CANNOT PROVE</dt><dd>That the expenditure is waste, avoidable, or a measure of current frontline service performance.</dd></div></dl></article>
  </div></section>;
}
