import {fireEvent,render,screen} from '@testing-library/react'; import userEvent from '@testing-library/user-event'; import {describe,expect,it} from 'vitest'; import App from './App';
describe('semantic wall',()=>{
  it('keeps Britain and Health in one persistent canvas',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Health 19p/}));expect(screen.getByRole('button',{name:'Britain'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Health'})).toBeInTheDocument();expect(screen.getByRole('button',{name:/Hospitals/})).toBeInTheDocument()});
  it('flies from Health into hospital operations',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Health 19p/}));await userEvent.click(screen.getByRole('button',{name:/Hospitals/}));expect(screen.getByRole('button',{name:/Workforce/})).toBeInTheDocument();expect(screen.getByText(/Hospitals converts part/)).toBeInTheDocument()});
  it('steps back through semantic camera levels with Escape',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Health 19p/}));await userEvent.click(screen.getByRole('button',{name:/Hospitals/}));await userEvent.keyboard('{Escape}');expect(screen.getByRole('button',{name:/Hospitals/})).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Workforce/})).not.toBeInTheDocument();await userEvent.keyboard('{Escape}');expect(screen.queryByRole('button',{name:'Health'})).not.toBeInTheDocument()});
  it('opens evidence without removing the wall',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Workers & households/}));await userEvent.click(screen.getByRole('button',{name:/Inspect evidence/}));expect(screen.getByText('Challenge the number')).toBeInTheDocument();expect(screen.getByLabelText(/Pannable and zoomable/)).toBeInTheDocument()});
  it('adds contribution layer to the same world',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Contribution/}));expect(screen.getByText('CONTRIBUTION & RECEIPT')).toBeInTheDocument()});
  it('teaches the national grammar without blocking the wall',async()=>{render(<App/>);expect(screen.getByText(/Start here: who funds Britain/)).toBeInTheDocument();expect(screen.getByLabelText(/Pannable and zoomable/)).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Next'}));expect(screen.getByText(/Borrowing enters differently/)).toBeInTheDocument()});
  it('makes timeline changes visible in place',()=>{render(<App/>);const timeline=screen.getByRole('slider',{name:/Demo year timeline/});fireEvent.change(timeline,{target:{value:'0'}});expect(screen.getByText('2005')).toBeInTheDocument();fireEvent.change(timeline,{target:{value:'4'}});expect(screen.getByText(/Health gained 3p of every £1/)).toBeInTheDocument();expect(screen.getByLabelText(/Changes from 2005 to 2025/)).toBeInTheDocument()});
  it('pairs related spend and outcome direction without causal language',()=>{render(<App/>);expect(screen.getAllByText('RELATED SPEND').length).toBeGreaterThan(0);expect(screen.getByText(/SPEND TREND ≠ PROOF OF CAUSE/)).toBeInTheDocument()});
  it('explains the Health allocation to delivery chain',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Health 19p/}));expect(screen.getByText(/Britain allocates 19p of every £1 here/)).toBeInTheDocument();expect(screen.getByText('care systems')).toBeInTheDocument();expect(screen.getByText('patients & communities')).toBeInTheDocument()});
  it('encodes national magnitude as area, ribbon and ranked labels',()=>{render(<App/>);const workers=screen.getByRole('button',{name:/Workers & households/});const business=screen.getByRole('button',{name:/Business/});expect(workers.style.getPropertyValue('--node-size')).not.toBe(business.style.getPropertyValue('--node-size'));expect(screen.getByText('#1 SOURCE CATEGORY')).toBeInTheDocument();expect(screen.getByText('#1 DESTINATION')).toBeInTheDocument();expect(screen.getByText('ONE NATIONAL POOL')).toBeInTheDocument()});
  it('reveals illustrative funding composition in the same world',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Workers & households/}));expect(screen.getByLabelText(/Workers & households illustrative composition/)).toBeInTheDocument();expect(screen.getByText(/RECEIPTS ASSOCIATED WITH/)).toBeInTheDocument();expect(screen.getByText('Income Tax')).toBeInTheDocument();expect(screen.getByText('Employee NI')).toBeInTheDocument()});
  it('reveals a spending composition without leaking Health detail',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Pensions/}));expect(screen.getByText(/THIS ALLOCATION CONTAINS/)).toBeInTheDocument();expect(screen.getByText('State pension')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Hospitals/})).not.toBeInTheDocument()});
});
