import {render,screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {describe,expect,it} from 'vitest';
import App from './App';
import nationalCss from './national.css?raw';
import nationalSource from './components/NationalWall.tsx?raw';

describe('approved £100 national Wall',()=>{
  it('states the public-money question in the primary composition',()=>{render(<App/>);expect(screen.getByRole('heading',{name:'Where Britain’s £100 comes from'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Where Britain’s £100 goes'})).toBeInTheDocument();expect(screen.getByText('of every £100')).toBeInTheDocument()});
  it('shows the reconciled real national pool',()=>{render(<App/>);expect(screen.getAllByText('£1.360tn').length).toBeGreaterThan(0);expect(screen.getAllByText('£100').length).toBeGreaterThan(0);expect(screen.getByText('Raised or borrowed')).toBeInTheDocument()});
  it('uses the approved stable source order',()=>{render(<App/>);const sources=screen.getAllByRole('button',{name:/percent\. Previous:/}).slice(0,6);expect(sources[0]).toHaveAccessibleName(/Income & social contributions £45, 44.9 percent/);expect(sources[1]).toHaveAccessibleName(/Businesses £9.8/)});
  it('orders Health as the largest destination with sensible display precision',()=>{render(<App/>);const health=screen.getByRole('button',{name:/Health & social care £23, 23.1 percent/});expect(health).toHaveTextContent('£23');expect(health).toHaveTextContent('23.1%');expect(health).toHaveTextContent(/prev/)});
  it('keeps borrowing visibly separate from receipts',()=>{render(<App/>);const borrowing=screen.getByRole('button',{name:/Borrowing £9.5/});expect(borrowing).toHaveClass('borrowing');expect(borrowing).toHaveTextContent('Fills the gap · not revenue')});
  it('treats technical reconciliation as not a service',()=>{render(<App/>);const technical=screen.getByRole('button',{name:/Accounting & statistical adjustments/});expect(technical).toHaveClass('technical');expect(technical).toHaveTextContent('NOT A SERVICE')});
  it('switches numeric hierarchy without changing taxonomy',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:'£ BILLIONS'}));expect(screen.getByRole('button',{name:/Health & social care £313.7bn, 23.1 percent/})).toHaveTextContent('23.1%');expect(screen.getByRole('button',{name:/Income & social contributions £610.7bn, 44.9 percent/})).toBeInTheDocument()});
  it('keeps the selected unit in the shareable URL',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:'£ BILLIONS'}));expect(location.search).toContain('unit=bn')});
  it('offers exactly the five accepted complete outturns',()=>{render(<App/>);['2021–22','2022–23','2023–24','2024–25'].forEach(period=>expect(screen.getByRole('button',{name:period})).toBeInTheDocument());expect(screen.getByRole('button',{name:/2025–26LATEST/})).toBeInTheDocument()});
  it('updates the same fiscal Wall while preserving the story chronology',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:'2021–22'}));expect(screen.getByRole('button',{name:/Health & social care £24.6/})).toBeInTheDocument();expect(screen.getByRole('region',{name:'How We Got Here — Immigration'})).toBeInTheDocument()});
  it('makes direct and stepped year exploration primary',async()=>{const{container}=render(<App/>);await userEvent.click(screen.getByRole('button',{name:'2024–25'}));expect(container.querySelector('.year-matrix article.selected')).toHaveTextContent('Conservative → Labour');expect(container.querySelector('.year-matrix article.selected')).toHaveTextContent(/Handover: 5 July 2024/);await userEvent.click(screen.getByRole('button',{name:'NEXT YEAR →'}));expect(container.querySelector('.year-matrix article.selected')).toHaveTextContent('Labour · Keir Starmer');await userEvent.click(screen.getByRole('button',{name:'← PREVIOUS YEAR'}));expect(container.querySelector('.year-matrix article.selected')).toHaveTextContent('Conservative → Labour')});
  it('supports left and right keyboard comparison from the year selector',async()=>{const{container}=render(<App/>);await userEvent.click(screen.getByRole('button',{name:/2025–26LATEST/}));const selector=screen.getByLabelText('Fiscal year selector');selector.focus();await userEvent.keyboard('{ArrowLeft}');expect(container.querySelector('.year-matrix article.selected')).toHaveTextContent('Conservative → Labour');await userEvent.keyboard('{ArrowRight}');expect(container.querySelector('.year-matrix article.selected')).toHaveTextContent('Labour · Keir Starmer')});
  it('opens evidence in place',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Income & social contributions/}));expect(screen.getByText('Challenge the number')).toBeInTheDocument();expect(screen.getByRole('main')).toHaveClass('national-wall')});
  it('loads the Immigration evidence chronology without changing the fiscal Wall',()=>{render(<App/>);expect(screen.getByRole('region',{name:'How We Got Here — Immigration'})).toBeInTheDocument();expect(screen.getByText(/Chronology is not causation/)).toBeInTheDocument();expect(screen.getByRole('button',{name:/Health & social care £23/})).toBeInTheDocument()});
  it('opens story evidence in place',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:'2021–22'}));await userEvent.click(screen.getByRole('button',{name:/Graduate route opens/}));expect(screen.getByRole('heading',{name:'Graduate route opened'})).toBeInTheDocument();expect(screen.getByText(/chronology alone is never treated as causation/i)).toBeInTheDocument()});
  it('contains proportional physical unit tokens and flow paths',()=>{const{container}=render(<App/>);expect(container.querySelectorAll('.unit-tokens i').length).toBeGreaterThan(190);expect(container.querySelectorAll('.editorial-flows path')).toHaveLength(20)});
  it('never renders or references the rejected national scene system',()=>{const{container}=render(<App/>);expect(container.querySelector('.scene')).toBeNull();expect(nationalSource).not.toMatch(/sourceScene|destinationScene|scene-x|scene-y|className="scene"|fiscal-sources-v1|fiscal-destinations-v1/);expect(nationalCss).not.toMatch(/\.scene|fiscal-sources-v1|fiscal-destinations-v1/)});
  it('uses consistent functional icons and visible percentages in fiscal rows',()=>{const{container}=render(<App/>);expect(container.querySelectorAll('.fiscal-row .category-icon svg')).toHaveLength(20);expect(screen.getByRole('button',{name:/Health & social care/})).toHaveTextContent('23.1%')});
});
